services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: autoria
      POSTGRES_USER: autoria
      POSTGRES_PASSWORD: autoria_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U autoria"]
      interval: 5s
      timeout: 5s
      retries: 5

  scraper:
    build: .
    env_file: .env
    environment:
      DATABASE_URL: postgresql://autoria:autoria_password@db:5432/autoria
    volumes:
      - ./dumps:/app/dumps
      - ./logs:/app/logs
    depends_on:
      db:
        condition: service_healthy

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  postgres_data:
